---
title: "Methodology_report"
output: html_document
---

```{r setup, include=FALSE}
library(DT)
#library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)
source('utils_exp_d/tools.R')
sample_data_by_name <- sample_data(wine) 

```

## Descriptive

#TODO: falta todo el analisis

```{r echo=FALSE}
sample_data_by_name %>%
  ggplot(aes(x= name, y=value, color = quality)) +
  geom_boxplot() +
  facet_wrap(~name, scales = 'free')
```

## Including Plots

You can also embed plots, for example:

```{r echo=FALSE, warning=FALSE}
# show the most important result of all models of all possible combination
all_median <- var_interest %>% 
  map(~median_variable(sample_data_by_name,.)) %>%
  suppressMessages()

all_median %>%
  map(~general_models(.)) %>%
  enframe() %>%
  unnest() %>%
  mutate(across(where(is.numeric), round, 3)) %>%
  DT::datatable( extensions = 'FixedColumns',
                    rownames= FALSE,
                    filter = 'top',
                    options = list(
                      pageLength = 10,
                      autoWidth = TRUE,
                      columnDefs = 
                        list(list(width = '70%', targets = c(0,7))),
                      scrollX = TRUE,
                      escape = T))
```

Entre ellas podemos notar que la mayoria de aquellas donde los residuos de la interaccion poseen una distribucion normal.
solo se tiene el caso entre el pH y la volatilidad del acido, la cual detallaremos a continuacion:

```{r echo=FALSE, warning=FALSE}
var_quality <- "pH"
var_trt <- "volatile_acidity"

# ref
data_wine_var <- median_variable(sample_data_by_name,var_quality)  %>%
  suppressMessages()

data_wine_var %>%
            as.data.frame() %>%
            filter(var == var_trt) %>%
            select(quality, value_category, value) %>%
  as.data.frame()
```

a
```{r echo=FALSE, warning=FALSE}
graph_interst(data_wine_var,var_trt) %>%
  suppressMessages()
```

a
```{r echo=FALSE, warning=FALSE}
sample_variables_int <- data_wine_var %>%
  as.data.frame() %>%
  filter(var == var_trt) %>%
  select(quality, value_category, var, value) 

result <- lm(value ~ value_category + quality, data = sample_variables_int)
model <- aov(result)

# resultado que imprimire sobre los que
# generaron algun tipo de interes a nivel de significancia
summary(model)
```
a
```{r}
# print
shapiro.test(model$residuals)
bartlett.test(sample_variables_int$value, sample_variables_int$quality)
bartlett.test(sample_variables_int$value, sample_variables_int$value_category)
```
a
#```{r}
# Diagnostics of model
#plot(lm(value ~ trt + bq, data = sample_wine))
# TODO : cambiar la grafica

#```